title: My CTF Writeups
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A site for hosting my CTF writeups.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
